files_to_load: [
  # "/work/kschmidt/NEEDLE/test_analysis/data/cf_store/test_analysis/cf.SelectEvents/run2_2016_nano_v9/ttbar_dl/nominal/calib__test/sel__ttbar_dl/remote2/columns_*.parquet",
  "/ceph/kschmidt/needle/fair_universe/input_data/train/data/data.parquet",
]
features_columns: ['PRI_lep_pt']
labels_columns: ['PRI_n_jets']
max_number_events: 100000
total_epoch: 20
batch_size: 64
num_workers: 4  # has to match the number of CPU cores made available by LAW
