custom_settings:
  use_test_data: true
  root_dir: ${if:${custom_settings.use_test_data}, "examples/fair_universe_demo/test_data", "${oc.env:FAIR_UNIVERSE_DATA}"}

results_path: ${if:${custom_settings.use_test_data}, "runs/fair_universe_demo_test", "runs/fair_universe_demo_full"}

estimators:
  nf_signal_1jet:
    model: cnf
    model_override:
      num_jets: 1
    datamodule: cnf
    datamodule_override:
      num_jets: 1
      train_on_signal: true
    trainer: cnf
    expands:
      systematics:
        c_0.5:
          model_override:
            c: 0.5
        c_2.0:
          model_override:
            c: 2.0
  nf_signal_2jet:
    model: cnf
    model_override:
      num_jets: 2
    datamodule: cnf
    datamodule_override:
      num_jets: 2
      train_on_signal: true
    trainer: cnf
    expands:
      systematics:
        c_0.5:
          model_override:
            c: 0.5
        c_2.0:
          model_override:
            c: 2.0
  nf_background_1jet:
    model: cnf
    model_override:
      num_jets: 1
    datamodule: cnf
    datamodule_override:
      num_jets: 1
      train_on_signal: false
    trainer: cnf
    expands:
      systematics:
        c_0.5:
          model_override:
            c: 0.5
        c_2.0:
          model_override:
            c: 2.0
  nf_background_2jet:
    model: cnf
    model_override:
      num_jets: 2
    datamodule: cnf
    datamodule_override:
      num_jets: 2
      train_on_signal: false
    trainer: cnf
    expands:
      systematics:
        c_0.5:
          model_override:
            c: 0.5
        c_2.0:
          model_override:
            c: 2.0
  classifier:
    requires:
      - nf_background_1jet
      - nf_background_2jet
      - nf_signal_1jet
      - nf_signal_2jet
    model: classifier
    datamodule: classifier
    trainer: classifier

downstream_tasks:
  histogram:
    args:
      _target_: examples.fair_universe_demo.stats.histogram.HistogramTask
      root_dir: ${custom_settings.root_dir}
      json_save_path: "${results_path}/hist.json"
  neyman:
    requires: ["histogram"]
    args:
      _target_: examples.fair_universe_demo.stats.neyman.NeymanTask
      hist_path: "${results_path}/hist.json"
      output_path: "${results_path}/neyman.json"
      root_dir: ${custom_settings.root_dir}
  predict:
    requires: ["neyman"]
    args:
      _target_: examples.fair_universe_demo.stats.predict.PredictTask
      hist_path: "${results_path}/hist.json"
      root_dir: ${custom_settings.root_dir}
      neyman_path: "${results_path}/neyman.json"
      output_path: "${results_path}/prediction.json"
  eval:
    requires: ["predict"]
    args:
      _target_: examples.fair_universe_demo.stats.eval.EvalTask
      root_dir: "${custom_settings.root_dir}"
      test_settings_path: "examples/fair_universe_demo/test_settings.json"
      predict_path: "${results_path}/prediction.json"
      output_path: "${results_path}/eval.json"
  plot:
    requires: ["eval"]
    args:
      _target_: examples.fair_universe_demo.stats.plot.PlottingTask
      root_dir: "${custom_settings.root_dir}"
      test_settings_path: "examples/fair_universe_demo/test_settings.json"
      ingestion_results_path: "${results_path}/eval.json"
      plot_save_dir: "${results_path}/plots"
