estimators:
  nf_signal_1jet:
    model: cnf
    model_override:
      num_jets: 1
    datamodule: cnf
    datamodule_override:
      num_jets: 1
      train_on_signal: true
    trainer: cnf
    expands:
      systematics:
        c_0.5:
          model_override:
            c: 0.5
        c_2.0:
          model_override:
            c: 2.0
  nf_signal_2jet:
    model: cnf
    model_override:
      num_jets: 2
    datamodule: cnf
    datamodule_override:
      num_jets: 2
      train_on_signal: true
    trainer: cnf
    expands:
      systematics:
        c_0.5:
          model_override:
            c: 0.5
        c_2.0:
          model_override:
            c: 2.0
  nf_background_1jet:
    model: cnf
    model_override:
      num_jets: 1
    datamodule: cnf
    datamodule_override:
      num_jets: 1
      train_on_signal: false
    trainer: cnf
    expands:
      systematics:
        c_0.5:
          model_override:
            c: 0.5
        c_2.0:
          model_override:
            c: 2.0
  nf_background_2jet:
    model: cnf
    model_override:
      num_jets: 2
    datamodule: cnf
    datamodule_override:
      num_jets: 2
      train_on_signal: false
    trainer: cnf
    expands:
      systematics:
        c_0.5:
          model_override:
            c: 0.5
        c_2.0:
          model_override:
            c: 2.0
  classifier:
    requires:
      - nf_background_1jet
      - nf_background_2jet
      - nf_signal_1jet
      - nf_signal_2jet
    model: classifier
    datamodule: classifier
    trainer: classifier

results_path: runs/fair_universe_demo_test
