number_events: [1e3, 1e4, 1e5, 1e6, -1]
number_workers: [0, 1, 2, 3, 4, 5, 6, 7, 8]
batch_sizes: [32, 64, 128, 256, 512, 1024, 2048]
dataset_types: [
  "PaddedEagerDataset",
  "PaddedTorchDataset",
  "ParticleDaskChunked",
]
