_target_: examples.fair_universe_demo.models.classifier_datamodule.ClassifierDatamodule
root_dir: ${if:${custom_settings.use_test_data}, "examples/fair_universe_demo/test_data", "${oc.env:FAIR_UNIVERSE_DATA}"}
