defaults:
  - data: columnflow
  - variables: default
  - _self_
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

verbose: True
only_plot: False
format: "automatic"
